In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '20'

import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import seaborn as sns
import time

## Loading dataset

In [2]:
movies_df = pd.read_csv('./temp/ml-latest-small/movies.csv')
# In collaborative filtering method, we imagine there is no information about the movies like their categories
movies_df = movies_df.drop('genres', axis=1) 
movies_df.index.name = 'index'
# helper dictionaries to help memory usage for embeddings
index_to_movieId = dict(movies_df.movieId)
movieId_to_index = {v:k for k, v in index_to_movieId.items()}
movies_df = movies_df.drop('movieId', axis=1)
movies_df

title
index                                           
0                               Toy Story (1995)
1                                 Jumanji (1995)
2                        Grumpier Old Men (1995)
3                       Waiting to Exhale (1995)
4             Father of the Bride Part II (1995)
...                                          ...
9737   Black Butler: Book of the Atlantic (2017)
9738                No Game No Life: Zero (2017)
9739                                Flint (2017)
9740         Bungo Stray Dogs: Dead Apple (2018)
9741         Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 1 columns]

In [3]:
users_df = pd.read_csv('./temp/ml-latest-small/ratings.csv')
users_df = users_df.drop('timestamp', axis=1)
users_df['index'] = users_df['movieId'].map(lambda x: movieId_to_index[x])

# Take the average rating for mean normalization
average_rating = users_df.drop('userId', axis=1).groupby('movieId').mean()

users_df = users_df.set_index('index')
users_df = users_df.drop('movieId', axis=1)

users_df

userId  rating
index                
0           1     4.0
2           1     4.0
5           1     4.0
43          1     5.0
46          1     5.0
...       ...     ...
9434      610     4.0
9461      610     5.0
9462      610     5.0
9463      610     5.0
9503      610     3.0

[100836 rows x 2 columns]

### Create Movie/User rating dataset

In [4]:
movie_rating_df = users_df.join(movies_df, on='index')
# save the titles mapping, movieId to title, for evaluation
titles = movie_rating_df['title']
movie_rating_df = movie_rating_df.drop('title', axis=1)
movie_rating_df.pivot_table(values='rating', index='index', columns='userId').fillna(0)

userId  1    2    3    4    5    6    7    8    9    10   ...  601  602  603  \
index                                                     ...                  
0       4.0  0.0  0.0  0.0  4.0  0.0  4.5  0.0  0.0  0.0  ...  4.0  0.0  4.0   
1       0.0  0.0  0.0  0.0  0.0  4.0  0.0  4.0  0.0  0.0  ...  0.0  4.0  0.0   
2       4.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3       0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9737    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9738    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9739    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9740    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9741    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId  604  605  606  607  608  609  610  
index                                      
0       3.0  4.0  2.5  4.0  2.5  3.0  5.0  
1       5.0  3.5  0.0  0.0  2.0  0.0  0.0  
2       0.0  0.0  0.0  0.0  2.0  0.0  0.0  
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4       3.0  0.0  0.0  0.0  0.0  0.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  
9737    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9738    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9739    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9740    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9741    0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[9724 rows x 610 columns]

### Getting data ready

In [58]:
from sklearn.model_selection import train_test_split

movies = movie_rating_df.index.values
users = movie_rating_df['userId'].values
Y = movie_rating_df['rating'].values.astype('float32')


# mean normalize the labels
mu = np.mean(Y, axis=0)
Y = Y - mu


# split the data into training set and validation set
training_movies, test_movies, training_users, test_users, training_ratings, test_ratings = train_test_split(movies,
                                                                                                            users, 
                                                                                                            Y,
                                                                                                            test_size=0.2, shuffle=True)
print(f'Training movies has the shape', training_movies.shape)
print(f'Training users has the shape', training_users.shape)
print(f'Training ratings has the shape', training_ratings.shape)
print()
print(f'Test movies has the shape', test_movies.shape)
print(f'Test users has the shape', test_users.shape)
print(f'Test ratings has the shape', test_ratings.shape)

Training movies has the shape (80668,)
Training users has the shape (80668,)
Training ratings has the shape (80668,)

Test movies has the shape (20168,)
Test users has the shape (20168,)
Test ratings has the shape (20168,)


### Create the pipeline

In [108]:
BATCH_SIZE = 1024
BUFFER = 1000
AUTOTUNE = tf.data.experimental.AUTOTUNE

train_ds = tf.data.Dataset.from_tensor_slices((training_movies, training_users, training_ratings))
train_ds = train_ds.shuffle(BUFFER)
train_ds = train_ds.batch(BATCH_SIZE, num_parallel_calls=AUTOTUNE)
train_ds = train_ds.prefetch(AUTOTUNE)

test_ds = tf.data.Dataset.from_tensor_slices((test_movies, test_users, test_ratings))
test_ds = test_ds.batch(BATCH_SIZE, num_parallel_calls=AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

In [109]:
for movie, user, rate in train_ds.take(1):
    print(movie)
    print(user)
    print(rate)

tf.Tensor([4245 4229 2526 ... 5995 3770 6626], shape=(1024,), dtype=int64)
tf.Tensor([428 567  59 ... 380 419 380], shape=(1024,), dtype=int64)
tf.Tensor(
[ 0.49844313 -3.0015569   0.49844313 ... -0.5015569   0.9984431
  0.49844313], shape=(1024,), dtype=float32)


## Define the model

In [110]:
from keras.layers import Dense, Activation, Dropout, Input, Dot, Embedding, Layer
from keras.losses import MeanSquaredError
from keras.optimizers import Adam
from keras.metrics import MeanAbsoluteError, Metric
from keras.models import Model
from keras.regularizers import L2

In [144]:
class CollaborativeFiltering(Model):
    def __init__(self, 
                 units,
                 num_movies, 
                 num_users, 
                 user_embedding_dim, 
                 movie_embbeding_dim):
        
        super(CollaborativeFiltering, self).__init__()
        self.user_embedding = Embedding(input_dim=num_users, 
                                        output_dim=user_embedding_dim, 
                                        name='user_embed')
        self.movie_embedding = Embedding(input_dim=num_movies, 
                                         output_dim=movie_embbeding_dim, 
                                         name='movie_embed')
        self.dot = Dot(axes=1, normalize=True, name='dot')

        self.build()

    
    def build(self):
        user = Input(shape=())
        movie = Input(shape=())
        self.call(movie, user)
        self.built = True
    
    def call(self, movie, user, training=False):
        user = self.user_embedding(user)
        movie = self.movie_embedding(movie)
        return self.dot([user, movie])

In [145]:
model = CollaborativeFiltering(units=128,
                               num_movies=np.unique(movies).shape[0] + 1, 
                               num_users=np.unique(users).shape[0] + 1, 
                               user_embedding_dim=64, 
                               movie_embbeding_dim=64)
model.summary()

Model: "collaborative_filtering_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_34 (Embedding)    (None, 64)                39104     
                                                                 
 embedding_35 (Embedding)    (None, 64)                622400    
                                                                 
 dense_17 (Dense)            multiple                  0 (unused)
                                                                 
 dot_17 (Dot)                (None, 1)                 0         
                                                                 
Total params: 661504 (2.52 MB)
Trainable params: 661504 (2.52 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [146]:
loss_func = MeanSquaredError()

In [147]:
def get_scheduler(initial_learning_rate=1e-3, min_learning_rate=1e-5, weight=0.9):
    def func(epoch):
        return max(initial_learning_rate * weight ** (epoch), min_learning_rate)
    return func

In [148]:
train_mae = MeanAbsoluteError(name='train_mae')
validation_mae = MeanAbsoluteError(name='test_mae')
optimizer = Adam()
scheduler = get_scheduler(initial_learning_rate=3e-3, weight=0.95)

## Train

In [149]:
@tf.function
def training_step(movie, user, y_true):
    loss = 0.0
    with tf.GradientTape() as tape:
        y_pred = model(movie, user, training=True)
        loss = loss_func(y_true, y_pred)
        train_mae.update_state(y_true, y_pred)
        
    variables = model.trainable_variables
    grads = tape.gradient(loss, variables)
    optimizer.apply_gradients(zip(grads, variables))
    return loss

In [150]:
@tf.function
def validation_step(movie, user, y_true):
    y_pred = model(movie, user, training=False)
    loss = loss_func(y_true, y_pred)
    validation_mae.update_state(y_true, y_pred)
    return loss

In [151]:
EPOCHS = 100
train_mean_losses = []
valid_mean_losses = []
train_maes = []
valid_maes = []

for epoch in range(EPOCHS):
    train_mae.reset_states()
    validation_mae.reset_states()
    mean_train_loss = 0.0
    mean_valid_loss = 0.0
    start = time.time()
    learning_rate = scheduler(epoch)
    optimizer.learning_rate = learning_rate
    print(f'Epoch {epoch + 1:>3}')

    for step, (movie, user, y_true) in enumerate(train_ds):
        loss = training_step(movie, user, y_true)
        
        mae = train_mae.result()
        mean_train_loss = mean_train_loss + (1 / (step + 1)) * (loss - mean_train_loss)
        end = time.time()
        print(f'\r{int(end - start):>3} sec | Step {step:>3}\tLoss: {mean_train_loss:>2.4f}\t MAE: {mae:>2.4f}', end='')
    print()
    train_mean_losses.append(mean_train_loss)
    train_maes.append(mae)

    for step, (movie, user, y_true) in enumerate(test_ds):
        loss = validation_step(movie, user, y_true)

        mae = validation_mae.result()
        mean_valid_loss = mean_valid_loss + (1 / (step + 1)) * (loss - mean_valid_loss)
        end = time.time()
        print(f'\r{int(end - start):>3} sec | Step {step:>3}\tLoss: {mean_valid_loss:>2.4f}\t MAE: {mae:>2.4f}', end='')
    print()
    valid_mean_losses.append(mean_valid_loss)
    valid_maes.append(mae)

history = {'loss':train_mean_losses, 'val_loss':valid_mean_losses, 'mae':train_maes, 'val_mae':valid_maes}

Epoch   1
  6 sec | Step  78	Loss: 1.0757	 MAE: 0.8278
  6 sec | Step  19	Loss: 1.0077	 MAE: 0.7944
Epoch   2
  1 sec | Step  78	Loss: 0.7192	 MAE: 0.6494
  1 sec | Step  19	Loss: 0.8895	 MAE: 0.7319
Epoch   3
  0 sec | Step  78	Loss: 0.6132	 MAE: 0.5906
  0 sec | Step  19	Loss: 0.8506	 MAE: 0.7123
Epoch   4
  0 sec | Step  78	Loss: 0.5756	 MAE: 0.5691
  0 sec | Step  19	Loss: 0.8339	 MAE: 0.7044
Epoch   5
  0 sec | Step  78	Loss: 0.5581	 MAE: 0.5589
  0 sec | Step  19	Loss: 0.8253	 MAE: 0.7005
Epoch   6
  0 sec | Step  78	Loss: 0.5482	 MAE: 0.5531
  0 sec | Step  19	Loss: 0.8201	 MAE: 0.6981
Epoch   7
  0 sec | Step  78	Loss: 0.5415	 MAE: 0.5491
  0 sec | Step  19	Loss: 0.8167	 MAE: 0.6967
Epoch   8
  0 sec | Step  78	Loss: 0.5367	 MAE: 0.5461
  0 sec | Step  19	Loss: 0.8144	 MAE: 0.6956
Epoch   9
  0 sec | Step  78	Loss: 0.5331	 MAE: 0.5439
  0 sec | Step  19	Loss: 0.8127	 MAE: 0.6949
Epoch  10
  0 sec | Step  78	Loss: 0.5300	 MAE: 0.5419
  0 sec | Step  19	Loss: 0.8115	 MAE: 0.6944


## Evaluation

In [152]:
unique_movies = np.unique(movies)
test_users = (np.ones(unique_movies.shape[0]) * 249).astype('float32')
test_movies = unique_movies.astype('float32')
pred = model(test_movies, test_users, training=False)[:, 0]
indx_pred = np.argsort(pred, axis=0)[::-1]

for i in range(10):
    print(titles.iloc[indx_pred[i]])
    print(pred[indx_pred[i]].numpy() + mu)
    print()

Beneath the Planet of the Apes (1970)
4.4919667

The Raid 2: Berandal (2014)
4.4866266

Third Man, The (1949)
4.482878

Conan the Destroyer (1984)
4.373156

Nine to Five (a.k.a. 9 to 5) (1980)
4.349896

Matrix, The (1999)
4.3490014

Braveheart (1995)
4.3328705

The Imitation Game (2014)
4.3306036

Angels in the Outfield (1994)
4.3225784

Big Top Pee-Wee (1988)
4.303034



In [153]:
max_loss = 0
y_pred = model(test_movies, test_users, training=False)
for i in range(100):
    y_hat = y_pred[i].numpy()
    y_true = test_ratings[i]
    print(f'Predicted {y_hat[0] + mu:>2.2} and the true rating was {y_true + mu:>2.2}')
    max_loss = max(max_loss, np.abs(y_hat - y_true))

Predicted 4.1 and the true rating was 4.5
Predicted 3.6 and the true rating was 2.5
Predicted 3.6 and the true rating was 3.0
Predicted 3.2 and the true rating was 1.0
Predicted 3.3 and the true rating was 5.0
Predicted 4.2 and the true rating was 3.0
Predicted 3.2 and the true rating was 3.0
Predicted 3.1 and the true rating was 3.0
Predicted 3.2 and the true rating was 2.0
Predicted 3.7 and the true rating was 1.5
Predicted 3.7 and the true rating was 0.5
Predicted 3.1 and the true rating was 5.0
Predicted 3.5 and the true rating was 3.5
Predicted 3.8 and the true rating was 4.5
Predicted 3.4 and the true rating was 3.0
Predicted 4.1 and the true rating was 2.5
Predicted 3.8 and the true rating was 4.5
Predicted 3.6 and the true rating was 4.0
Predicted 3.2 and the true rating was 2.0
Predicted 3.3 and the true rating was 4.0
Predicted 3.7 and the true rating was 5.0
Predicted 3.6 and the true rating was 4.0
Predicted 3.4 and the true rating was 5.0
Predicted 3.3 and the true rating 

In [154]:
max_loss

array([3.1654434], dtype=float32)

In [155]:
model.save('./models/collaborative_filtering_v1.tf')

INFO:tensorflow:Assets written to: ./models/collaborative_filtering_v1.tf/assets


INFO:tensorflow:Assets written to: ./models/collaborative_filtering_v1.tf/assets
